#import "Basic";
#import "Hash_Table";


badv3 :: () {
	data : [..] string;

if (false) {
	array_add(*data, "vJrwpWtwJgWrhcsFMMfFFhFp");
	array_add(*data, "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL");
	array_add(*data, "PmmdzqPrVvPwwTWBwg");
	array_add(*data, "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn");
	array_add(*data, "ttgJtRGJQctTZtZT");
	array_add(*data, "CrZsJsPPZsGzwwsLwLmpwMDw");
}
else {
	array_add(*data, "vJrrdQlGBQWPTBTF");
	array_add(*data, "fcpTMnMqMfTnZpgMfPbFBWzHPpBPzbCPPH");
	array_add(*data, "mcVMfcsqZgmgVcmfgcmZmqZNJhrlrdhNhDdrRRJSvDTRhJlD");
	array_add(*data, "pMFRmLwHMbRPmMbPPddvqqrrNSTFVttdrN");
	array_add(*data, "hgfpgCGZcjpcgfvNtdrtjvrdtSrd");
	array_add(*data, "gZgsBBBlZggBGhsfhpzlzLDLmLRDRMLDPw");
	array_add(*data, "hChhMFCvqtTMwbSSHgTZWHZd");
	array_add(*data, "jjBNPjJJNfsNjVnVJJNcNfPwGbSbDZnZZgHrddwHrrgWGb");
	array_add(*data, "mBBRRmBBQBmNJWhCzqllzhRCCv");
	array_add(*data, "lQgpngNgQvHdSgWwjMRmDjmMDHmm");
	array_add(*data, "zCLVzfzzbbCzsZZPbZPLfFJJMDWWRcDsmJRcjmwTmlRj");
	array_add(*data, "BblftzBtlFznptSQQQppNG");
	array_add(*data, "wJJwqCtCGRcVlqlM");
	array_add(*data, "BQpppjBQLczTrvHRjH");
	array_add(*data, "QQQFnmQWWRfnpQBpQpfDCwCdbPDCwbNNPtdJPCZw");
	array_add(*data, "gpJjshBpgjZGppJqBGJjJZzTwzTmcvzwwcmvwsCFdmcF");
	array_add(*data, "WPSSWWSQLVdDDfWltDWLPfttvFCVmzCCTFnmwcnnnCTCzVVv");
	array_add(*data, "tLldLltDQfflrRWNqBRjgHBpJNZjHj");
	array_add(*data, "bzVJjVnjbCGVLZQLmmsJZZQQ");
	array_add(*data, "RrwwzhPScWSwrhvZZvZlZvvSTsQS");
	array_add(*data, "HwFhzFWdPHfcPwPWPdhWffnngpjtnjgtpnfGCGnG");
	array_add(*data, "CPwQtftDQfPDBPBCfDDDCDptszcpVVddcRczVLVdccRGrLWs");
	array_add(*data, "FqlSnhlqhmhMbHqqSQlHbcrRrsWzRdzdWVzLRGRrVF");
	array_add(*data, "MbQmSnHZhqZMQMTJCttjCgPCwfgDwT");
	array_add(*data, "CCSpvHtZHSwftFtdtbfR");
	array_add(*data, "QJmNPmjjJNgNVNSzDlmRqbWlqWWfcqfWqbwfqR");
	array_add(*data, "MDhJzmSMDmsZrLhssrvh");
	array_add(*data, "ZhznnrLzcHhHSjsjSBSsBnSS");
	array_add(*data, "dTwqDdqDRQjNdwqjldggDvBJfmBfTSBbBSvfSJsmff");
	array_add(*data, "DjCldNglVwFVgZHHHzhCMcLhMC");
	array_add(*data, "vBnShjwwSshmQPmtJLpJtn");
	array_add(*data, "rDLFCWrClWCMWWVrbFVJqpQqpHmtbzJPQzJmzb");
	array_add(*data, "ZMCCDCMNrTWTrgScgGRhsvcsGLSG");
	array_add(*data, "LQpJglQQRjQsppfsQbjfbQlBgBhFhrvghhZCdPZZZthPgv");
	array_add(*data, "zVHDMSWVVMVWDzmnVMHDSMMzZvNFFrFvPCdmdFdNdrBPZhhd");
	array_add(*data, "ncqqSzMVCcGWVSCTWCDcVTffLLLbJsLLsRLblRQTps");
	array_add(*data, "zjGzLQtFzzRgwwLhVrqw");
	array_add(*data, "dfClCdHZsmffZDWlBZHCDBmhJbqTgbwgqbTnwrgrqRbT");
	array_add(*data, "HsdwPCsWDpDsBpfdWdHldWpsGvvccPvGcvzQvFQvccjNztQt");
	array_add(*data, "wmVVgFPrFdwJrlNHQHSHCCHL");
	array_add(*data, "tWBtvnBqZZMpcvmmqMBRCQQLCLWCHfNQQCSGWL");
	array_add(*data, "BBsnmcpqPswFsTws");
	array_add(*data, "BQRpFPJJJJPmPRqZNFVhcczHHzggwjBhghgzHw");
	array_add(*data, "snTsTLtrlvSSSslsGdcwmjhgggvjHhmH");
	array_add(*data, "nSsWWTtCbbDSnlRRZCfFRNZmCVJf");
	array_add(*data, "tRRMCWLtJWQLqLrmLHVLqmqh");
	array_add(*data, "JszPjSbGbsnGnSZprVpFhvFqvhrqZZ");
	array_add(*data, "zgbGSDBbPsTgbDBzzSDnDnPTcWlWJCQlNttNwwwMcMctcW");
	array_add(*data, "hlVRvPvzqqtRdwRRJsst");
	array_add(*data, "HHVNVBMBjHLTjVjwDjsbjJwbdmbbss");
	array_add(*data, "NBZHMCNVCCpgLTWggBpgNLTvqCPnGhQhCCGlqlhfcvvGfn");
	array_add(*data, "mwbfbfbDCqRJZRbCSvmfWTQFczTznnnFTFnrzJsz");
	array_add(*data, "BdhHlLjpjjjncSprnsSFWS");
	array_add(*data, "ljhVBPjSdHPRfZRZDvVRZM");
	array_add(*data, "tGqbqBSsntRgNqwNNVVHVN");
	array_add(*data, "hclFvJZvCDFppDpZpHNggMTwdlrMQNVgHM");
	array_add(*data, "CCFmcZLDFpvzZhCFJvZvmwjSRWsBLWsnfWjRRGGfnsst");
	array_add(*data, "GdGQQFdcMPwMdLFvWsNWFDLfss");
	array_add(*data, "SqjhtjnrbVznSztSqtzpjztVvTmNNmmfMMfDDMDDNTqfgsqv");
	array_add(*data, "rVhhZjppVrhpVzRbjSnzHPMwlJCJQdcRPPlPPcHJ");
	array_add(*data, "JVQLVgVZghFtFlhghtvSzsddmrdvssmzSWtd");
	array_add(*data, "HTMJCBMCjnwNBnCbTNwMdWfzvzsrsvffWbdsmfPr");
	array_add(*data, "BGnnpDnTjjHJwDBNpqlFQVQFQclcRFQqpR");
	array_add(*data, "BRhbrQDttbTTtRDtTRRzLHWZLZHGSqWLCBNWqLNL");
	array_add(*data, "fwFPPSjmsmJGLsNH");
	array_add(*data, "dvfSdvfVMjPTttTzczgTcd");
	array_add(*data, "dZgggwzgvsggtdstZTZgdfnhSJSSJDDhnDBdppnGnhSp");
	array_add(*data, "VQWRQWVCRLFGnThJCpFJ");
	array_add(*data, "LbmmbQVcHcmmlWjmVlVQNVRzvwwZvTrsrNwNwzZrMvfsqt");
	array_add(*data, "lDZQSlHDbLccRPQhCNhG");
	array_add(*data, "gtsntgvdvBvvqgsTgBggdrWRNzPhWczPbWcdWCccGGGP");
	array_add(*data, "sTBttvrFnnMTMJngbqfLlZLpwFVljwppZZDl");
	array_add(*data, "zNNNgqpgmLgqlHBHsMGslH");
	array_add(*data, "WdWFrFwhcwWRwhddcRWcdQbcDDslzBDszsHbGBDfbHfzVlVl");
	array_add(*data, "ZvhRrvPQwvWFQRZvFdJttSPgCmNppCNzJnJS");
	array_add(*data, "fCzRRNGfqNRvwpQhwrGcwZZT");
	array_add(*data, "gJnStgMmLhdHndSSTjcTrTpcmrjjcrrw");
	array_add(*data, "FFJBbdddFPPhFFNWCF");
	array_add(*data, "btrHRSBBSNLLRPLwhbhpqpfWhQppWZ");
	array_add(*data, "zCzTvvmgDvgDZhqWZZthtDZh");
	array_add(*data, "ttTjMsvCgRRLRSsBRG");
	array_add(*data, "LsSFFTTDWdCsmFTlLSsLDDRRQCvhpRQGNGQBJBhGGMNB");
	array_add(*data, "zqPtqZnjPPrPvJHBMHrJrMpv");
	array_add(*data, "VbqfjZfwgtfjPgZPgtwDLTLcTlcFdWLdcdVTJF");
	array_add(*data, "pfMCDmpHbdMQQdQFFG");
	array_add(*data, "gdjldRsVFRntQnqR");
	array_add(*data, "rlJVsWgWPWjsslSpDbScmSDPHfCd");
	array_add(*data, "lnFFGgBFBslDFGbFSjnNTjjppSrQHhnT");
	array_add(*data, "zcvmCRcvZmcZzWpTQhQrrTSPtHWH");
	array_add(*data, "CRccrZJmdJlwDJwgswGg");
	array_add(*data, "hllrrDzggGppgSSLNWgW");
	array_add(*data, "jlTlPwwqjjntVpWWPNnP");
	array_add(*data, "wjjJqvQjJjQJbTjlFqhBMzfDDmMCGBMHDCGb");
	array_add(*data, "jvQPhhtCRtfmqHHjqHHJsl");
	array_add(*data, "FFSTcBTBTMwFGCTwMTcGwTVnsHSJzqqJJJplmlpJHszZZzZD");
	array_add(*data, "dLMdVMNGBdGFMTNTRRLrQWCQhgWQbhgf");
	array_add(*data, "gdRgdgzzrvrzggDwgDGpPLzrbNljMTsbWWjWjZbTjLZMWcWj");
	array_add(*data, "tFfCQHJJnJMJTJjNNMjl");
	array_add(*data, "HmtffVttqHQmBCBQCqfFnCwRqpDvPRrGppRggNzdwgzp");
	array_add(*data, "DHSqzQbzWlRLDzMZNpVLgnpNLggw");
	array_add(*data, "cZcdTmPPthPdsvvdhPGTvJgwnpgjjTgNNwMVngNBjNfn");
	array_add(*data, "PPdJPvrtGtcFdFFchDRHDqHzZWSQQCrQWQ");
	array_add(*data, "BcgnLBLsFvRnGRRRlzfJbbPJzwHPwPFz");
	array_add(*data, "hCDjWMDVNfVllfzddw");
	array_add(*data, "qqMqpWCMjDTWNWTBLpgsgLvZwtGLLg");
	array_add(*data, "zczPgpGzhnbmbchhHwqwhSwfwHCFWw");
	array_add(*data, "VJdmVLlLdVJSJWHSTFwH");
	array_add(*data, "rlttQLVLdvvZpgcGbmDrzGMD");
	array_add(*data, "WSvtpqqtqccttVQpVvJNJSVNCmTlnCWwTTnWlBBBjwCBTlTP");
	array_add(*data, "ZgfPHfPfMHsDCwnlGBwTMGBM");
	array_add(*data, "rgdffZhPrrLsdLZpvcFSJJNvpJhcJv");
	array_add(*data, "qVdqJGvzgJzJgwzgWvdJzpblcRRWmLFFcLBmllFRRMRFRH");
	array_add(*data, "TGGSsSssNPTSLlRLcPHMmnPB");
	array_add(*data, "tTjTZtNGhrCjQNCjQQDTCSjZvfJbdgqrdpwqfVzwgzvdvVgb");
	array_add(*data, "VTmwcTVSMHwbMwbDVBTcMpJfpfnWqdJbZpJldfsjZn");
	array_add(*data, "hNtPhtzFzPQGCCGFFCGtnqQqWZWplsjWdlnlldJn");
	array_add(*data, "vRCRzvvFFFvhrRthPtLrtNGSwBVDScDSgHHjwwcBgSgTSL");
	array_add(*data, "dWCsWbWWchblsmbWVZqqsSpsGfBqBVBB");
	array_add(*data, "DtTtjPJrgjjtTTwgPwwjrTgnLqSBZQLqngQppqnfBVQfGp");
	array_add(*data, "PJPwwtDwHGGJtJRFHmhCFRCvdmHR");
	array_add(*data, "mMsMJSCjllsSSmBBclsMsJHDbcHqqbHpqHGbDZHbqHpb");
	array_add(*data, "RnQnGVnzGzFQgzWzpzvpqDHW");
	array_add(*data, "QVhRTfGLLFGTTFFwhnQVNfFwJsJsMjsBMrlsjrJlPSPlTrls");
	array_add(*data, "JNMJSVSGVCjnWZMZWWcH");
	array_add(*data, "gLTcqbqhqbbgzgnjpnjjWHnP");
	array_add(*data, "wqlbcrfTwrvcLBwwRtJwsNRstRsCCN");
	array_add(*data, "MlBssQBchZDLNJZgmvGg");
	array_add(*data, "fdzHMfHSzSprfgSvvJbmvDGNDW");
	array_add(*data, "PCHTRfjHnzHMzzfrCPCpMTlFhcFstqVwVCFllQcBtqss");
	array_add(*data, "TtFnnFJfDhtdfJJcFtfnsfcFjBjLDjHrDLrCjMjwCLLrZjrS");
	array_add(*data, "qQmWmQzvWpRQGvgpGGRGRzmWwZMwBLCHMZjbBBCLwrHSLrqr");
	array_add(*data, "MRllgRWWMlsJFnlFclJT");
	array_add(*data, "SRRrRDRBRTdbdMRZBZMprTCJCnWGvChJGzLSWWzsGhCs");
	array_add(*data, "wwqHPtFwjwTHLHvGTsGW");
	array_add(*data, "FlPtqTNVcTVtwtmjRbBZfQbfZbQmRRMR");
	array_add(*data, "WSWfQttffsHSfRRRStfnCsQQqlJpbhnrnmNzJbzqNbbrpmnb");
	array_add(*data, "FGFPddBcBwDPzpzbWlpzDbbh");
	array_add(*data, "ZPdPPLMFdGwFFGdwGdZwcZgTtSTVCsRRSgSRTQWTTtCTtH");
	array_add(*data, "vHsfGHTvSvHHHsGHctMgtHrJwbJJwrjgbrdzjWCrdrrw");
	array_add(*data, "hqZRLmmZpFhcLhFmrzJQbzzmQQJWJJbm");
	array_add(*data, "LNZFcpPlhBRhqDDllRtnMssGfBsnttGTnttT");
	array_add(*data, "VDVrLrZZcjrhhFrZppGlglGMPFwFWNQw");
	array_add(*data, "bzszSBHBWNGcscpN");
	array_add(*data, "TJqBqSfTBBqBHzJqddBqzcLnLjnhCRTvvRrnDrvrvZRn");
	array_add(*data, "GLzrNWbtMptHDmNDglgmlD");
	array_add(*data, "fZtcfCRvtBcQjdjgmmjj");
	array_add(*data, "RhBhhqfSPPpttrnPnVVW");
	array_add(*data, "BhVRJGwWqtHjZqTDLZ");
	array_add(*data, "gQnfpBdPNpQrPNSfBdndnpTTDFZttDLLzZzTzCLNLZZD");
	array_add(*data, "mQQPsgrldpgdBQgSbGVcmcRwGMWhwVwW");
	array_add(*data, "DrLCctBCLQtSSQcLbcQHWvvvlWHHnWlWBlNRRB");
	array_add(*data, "wqdmpgqsZhzGphwwpZGsppRvfnJsWfHWvfFfWFsfvlNN");
	array_add(*data, "mwmhVppTqpGqpNZpqTbSLLttDrDDtPQTtr");
	array_add(*data, "qwqmgnglDnlgtQzQJzJQhmWQ");
	array_add(*data, "pTpTpssdsVvNsdTSZGdSdjvCRcqcRcVWVczhWChtchzWcR");
	array_add(*data, "sGTvPqZvSGdZZGdsvNGdPHrFHFBDlDLwPgBFLLBB");
	array_add(*data, "BBBGsGGBrBBrqWVqRnWBBBWpzFwMhjMFSFPzzSwPFPpzzFvg");
	array_add(*data, "HtCdDdDctZDtbHCffcbddbNfvjvFSPFjMhMgLwPgjbFhjFFj");
	array_add(*data, "NJTDdltNgCNDZJJZCDJZDfJtrWWnQGBqlRVVlrBsnlrqqmnr");
	array_add(*data, "PwZhgbZSWSqqGznv");
	array_add(*data, "tTPVVmptcsrNrsTNpjRzqfHvvGfGWjfjqGzHWn");
	array_add(*data, "RVRtVDRmsRtrctmJDtgBBhBhbFgJPFFMFJgP");
	array_add(*data, "jPzzCCPzTtTfzrRtgSNVRHvFQVvbpQppVN");
	array_add(*data, "sSnDlBGBwJbFNplVlN");
	array_add(*data, "cLwSwdMhSwcBcsBZgWjCTCWfCLffrg");
	array_add(*data, "RSNPvTTNqFTSvNrSBvBGJGzmFMslgCMJCgmzlc");
	array_add(*data, "fDVfpptLWQfnVLffVHbQDQCclJzGGCtGmmGJmzMshzGh");
	array_add(*data, "VfQnWZfZDbdnVHWcfWnfHWVvPrTSNZqSwSqPjjvBwRqrNS");
	array_add(*data, "FLRpmRwcpjfzjSnD");
	array_add(*data, "tGvPNvBnPQggPQQvPgNHDjSSjDzzthjzfHrjlT");
	array_add(*data, "JGqvWNCCGQBWGBQvVLsCMMRLRnRMnwMc");
	array_add(*data, "fGJbzgBffCGpPGDVnG");
	array_add(*data, "mcTccshvbbdRNRsNjdLjnVlHVnHLqVpDpDqD");
	array_add(*data, "wdmsWvWssbZTcWvRhfzMQtrzMgrfrZJgfQ");
	array_add(*data, "NfSbvZHZNRSbQbbQgZrMjhLwMrjLjwHLCmmh");
	array_add(*data, "NTWdJBFcWJFcdsFJqcqPwqmjpMrLCMpLMwLP");
	array_add(*data, "dNJctnFBVfSGgvnfZz");
	array_add(*data, "GSnRJfGfRJgMDMGWnfzdmptpFJppLvwLwvLt");
	array_add(*data, "hbjZzrQbblqcLtpwlHvFplTH");
	array_add(*data, "qrzqbschrQCqqjPcCVcCGDfGMWDgWNGDDSfgnf");
	array_add(*data, "vmMpCdTndCvMdmnFcCRJWBJGcZJRJB");
	array_add(*data, "NDNwGzshPLrwVVNsjswhGzjFSfFFQQRSJWRBFcFRfsWFQB");
	array_add(*data, "NwNhNjVzhhzzrgzdqqvqtnqvlqdggG");
	array_add(*data, "MdPLVSSlMMVMmlLBBLFdvZNWqWztStttRRNqzqNGTq");
	array_add(*data, "DhJfhghhCgwChJgJwHHzbsHpnZRtTWqqfZRGTnWTZtNqNRWR");
	array_add(*data, "hwHpJbprwpQhDHDCbCCzsClBvrLMVFPvmPlMMVMdLrvj");
	array_add(*data, "DssDrqRsWsNfzfsWLRzjgTdBlgzFpMlgTFTglT");
	array_add(*data, "ttCZnSQmSQmgjGQGQgDlBp");
	array_add(*data, "bhDnCmbwVmCwwtZttPwbRWsRJcqWJfcfsfrqVrqq");
	array_add(*data, "ldBgTMTRvBDVnCCCTdSRTqNjbjSbPPPPqtfPqtPJFJ");
	array_add(*data, "cZHZrszLrrrZHrbNjNtbJCfqNJLt");
	array_add(*data, "GZzCzWZGGsGzmzZcmGssZzZVvnVdBDddRRDnVlWgRTDdBM");
	array_add(*data, "RjNrrjwGDDqqGJsHtzpMHHGz");
	array_add(*data, "QCbWgbShmBCCPClmmWFHzJzTbDdsMJsTtpTD");
	array_add(*data, "fffQfnSCWDBfhCDLRrNrwcrqVqwNqn");
	array_add(*data, "zmRrDRzqjmLLHzDjLsHLflJlVVJlWWTDTfdMtlWJ");
	array_add(*data, "pPQQnbvSpvNbgfgfVtMVJfgdtG");
	array_add(*data, "SnpnVFcPnNnPvpNSFNSbhHLhrjhCqRsRBRrHCLhzmC");
	array_add(*data, "CZZzlnCZNlGGcbVrbtVlMtct");
	array_add(*data, "MgFQDFgQRLLHhJgDFqQJQLgdtVTrttSrPSmcbmTtvSqvVSTV");
	array_add(*data, "hFQDDfMDfLgHwWfBzWwwsZGW");
	array_add(*data, "bHVDdHVHTPMvnSQnWSDQgDmm");
	array_add(*data, "GhrCJfbfrhfbRJcqGqlwZtnBRtBWSQgQWWnWQW");
	array_add(*data, "lfcCrqJhlfFqphpplNCrNVMPMPLbsLPLzFVHVLsVdz");
	array_add(*data, "VDhFCZhtFdPqwwcp");
	array_add(*data, "SvnvHNNnTvbwNNgnHwTHgwBTLcdqmmfmqLGmmTRLPfpdGP");
	array_add(*data, "BNWsHJgSnwgMMgMBBWMDVJjtjZrDJZzztJhjQr");
	array_add(*data, "HDsSHLRnpjbpbbRDbqLjLjjGGVffMVGMdvnfMcNvfBBGcB");
	array_add(*data, "TCzQQztwwNTMqMdBVv");
	array_add(*data, "hCQWmtCzZthPPZPrLjSbJqjSjLLFjLpr");
	array_add(*data, "ZrrZqJDcZSCFLLHBFcjjHF");
	array_add(*data, "TgvnDTlTtQwgBfwwwzLjGLdF");
	array_add(*data, "VbnVngMtvDTTVMQDQMDQlsbZJChCmCPhprrZqhqZSZPJ");
	array_add(*data, "glMGHBJTJJTplgwcCgcqcFhhbWncFm");
	array_add(*data, "sSswtPfRDmWcCqfchq");
	array_add(*data, "RZSdSzsVzNPSwSSQsdzSSQpGLjJTMpBGrJrLLrplZBpG");
	array_add(*data, "WQqqwLqQlnlWDwtbVbtCNfVbpV");
	array_add(*data, "dFTRjBPhcBgBrFhTPhrbVptJpNNbbtJCbJSL");
	array_add(*data, "hjcmcRmgPPcRcPDmHHzGLWmsDmzH");
	array_add(*data, "rWFmrRmmccSZJWvSLZTH");
	array_add(*data, "hDPhGbhSjtbpqJLvJHjLHTqj");
	array_add(*data, "pnplBlfBPPhlgfDbDhglPMMrwrRRSSncwccQzddzmC");
	array_add(*data, "LbccJCGzbcCJcfGczcnmNnvNmZNLSDZZWPWS");
	array_add(*data, "dwstRhTsrsFddPZqvNWP");
	array_add(*data, "BBggRrQstBwBRTHWTprRCHHGVljfCGCfcljHjbGV");
	array_add(*data, "FHVBSVDvnsFDwwSVwwvGVSMFWhWcWptMWchWMtPPcWtNNWcj");
	array_add(*data, "TgqJrJTRmRCNrbcLjprLnp");
	array_add(*data, "qQTlfdlZQgmfqqnFVznvQwvnsBsV");
	array_add(*data, "TGpDDMQGMZNtfvDJdtWd");
	array_add(*data, "jbrmstmllRmNvVhmmvJVhv");
	array_add(*data, "tbrRzFFLlRrjFlLlTQgLQwwLMwgTZBTB");
	array_add(*data, "QFgFWQQfSgLFGmtnnVmqCPWmPH");
	array_add(*data, "TTzjgTbRRqnRsCPCsP");
	array_add(*data, "NDMMgZjzcJvbjhMcjZbbbJJNpdpBfBvSBBQwBSQLQSpSplBG");
	array_add(*data, "zcRNsQSSMjRsNNZZFBLQHHFFBPWF");
	array_add(*data, "tvwCtgvqLJNnNBCH");
	array_add(*data, "fNNwqrqNMpTrDlcs");
	array_add(*data, "MMHMVPRJHJWvqzWctbtQQdQz");
	array_add(*data, "DFfNFffDnTllfTfFfmzsjqcdtQGQpbddQQbssn");
	array_add(*data, "mlFNCgFNNNLrmLFCThhhzJBvhSJPVhMgMh");
	array_add(*data, "PWjhljbHFhjbFMWhjbPfhbTGZvlGcGlCLvvwtGCNZGvc");
	array_add(*data, "SRqBqBrmQWQrgQrrqrJBLZNccLNZmTCtvTGtCvCt");
	array_add(*data, "rJDzDSSBrzdqQWDPHFMjMFdjHMVnbM");
	array_add(*data, "qqLwvvtrLFqqfqrjjjdBZfBCBBJdlT");
	array_add(*data, "ZGZpRZHbQDzDWRRRVdBzSSlBdzjjzdJJ");
	array_add(*data, "ZGpgNDQmWGDRmRpZMQbvPPtnnFnLsstFmnFrPL");
	array_add(*data, "TdhcfZhdZZdpdbPWttCWrrCN");
	array_add(*data, "MBMMqRLgpGpFFWbNsvLwvCPCCP");
	array_add(*data, "mpBMnBRMBGqJfZcfZZHZlhfm");
	array_add(*data, "CdmGdnMcMwHjhDtFFnrj");
	array_add(*data, "vPbVbPBPPpgpgWJpvTjqDZZqSHqVZShrDj");
	array_add(*data, "BppjjgvbJjbpNbzPfNcGCLlCRcmLLflllGcc");
	array_add(*data, "qDtgVttGFtlslStS");
	array_add(*data, "gCZbbHCjvJbZjCbJhHhHJrZcslJcLzLllcLNFssMSsTlSM");
	array_add(*data, "CWbWrZgWBQQBBpfdPm");
	array_add(*data, "hstPtCGtltlTClllPJLScVdPdJjLPJMV");
	array_add(*data, "NHRbDZDQSDFFjjdJ");
	array_add(*data, "RqbQpgBmqZvqZNQqgZmmbszpTtthtCswhjslwwpTWC");
	array_add(*data, "CVdwBJJdppbbwdBVrJbrJbGPlMFSLrjrPjmPFFmPRRDF");
	array_add(*data, "NNWHHhNZTcQWhnNFlmSSlRmLjnPPRF");
	array_add(*data, "qWsccHTZccsNsZcvTcNtStpBtbdVwpfBwbVCBq");
	array_add(*data, "lPQHNJhMPMPFlNMHBqZBwQwQwQZwcCqw");
	array_add(*data, "bWddDzbWbftdDSDbgttgnSDWccLwcvBczqcqGZzLccZTZwwc");
	array_add(*data, "spWrssWrnDtDpfSWDtsFqlFPjNMjRJVVNNPJNp");
	array_add(*data, "bCCfcWVLTHfSSdHwhH");
	array_add(*data, "sGQSZSzQJmmQsphwHHHsndnpHN");
	array_add(*data, "zPSqrmZPFCvFTbWMLV");
	array_add(*data, "tLtVBGLJqGqVGbzGSCsSsSqQsFvZCSQv");
	array_add(*data, "gRgdWlHTBHgjjHlWpWjWjrwdCfQRZFSssQQQZmQmMSvZfFMQ");
	array_add(*data, "lPHlpWgjTldprNWHNNdHjTctcLbVcnNJJGbVzBhnbhhJ");
	array_add(*data, "zVrSwzzJbVrbqFCVVVwVCztWDDtfTZsWDZTLZZmSWsDm");
	array_add(*data, "bpgHlgBbbGGGglBGRNvMpWfTDjmDfWDjfRZZWLtmZs");
	array_add(*data, "bGbvQHMpQccFJPPh");
	array_add(*data, "VGqCPmPjfGqCdMqVMhjhmPChDJDJzvrrbrBvrdrpnJDpJDQr");
	array_add(*data, "TSRsgHRSFHTlHvJvBDvvzlptbv");
	array_add(*data, "ZFLTsRRgZTgWscHTfWNWNPPBfGqmmMfV");
	array_add(*data, "TvTrrrCVCVwqjPrWfWhjfH");
	array_add(*data, "RRmgmnggltRgNpzRsdfqWWjdFdvNHfdh");
	array_add(*data, "zZlRzDGGZmbmmZbvGJVccwCMVcVVTLwDwC");
	array_add(*data, "QPsNlvvvSccbbNQcSPvDVSvzTLLCgRVzCJgTJpgCpphgzh");
	array_add(*data, "MDqHwFrMffgFpgpJLzTz");
	array_add(*data, "ZtdrffBrdqmBBmfwMtDtQPPPbjcNvnllnlbNtScn");
	array_add(*data, "HbbbcpTHHMMqNTCddCVBQvgPzJPJWQBQjvpBvQ");
	array_add(*data, "FFrDGtntFFwhrRFDFthfRhRmSJPJvvJZjZjWJJvJQJnvWjjg");
	array_add(*data, "rtfFfLmLRmNgdHqcLNHd");
	array_add(*data, "FpFHCFWtFSnCWnBfJJfgMJDGHDGGsG");
	array_add(*data, "rhrLrrhLrbtZThLfgsfGNDfgTgNcDs");
	array_add(*data, "QmPjbdqjmbbbrmhQqQZrZStRdlnnFdlRzVVVWlnpzR");
	array_add(*data, "bBMwwjzhbjhssvsGZBSZLr");
	array_add(*data, "JFtnDtRzJtffJHWNtHncRRrvGZvSnllZZZsgvlnvVvlv");
	array_add(*data, "RRPHPHFPHHdcHtzNfMQhdCwbqCmbMChhqq");
	array_add(*data, "pWGdFSWwwjLdvgNNvggl");
	array_add(*data, "mTNbmRPHmmVNmvZhnhBssBlhnb");
	array_add(*data, "HPTzRPffJJNzjCFpDWDz");
	array_add(*data, "MHlgzsqHlbmzgsHzlsbcRWPdPtjZFqhGGdrPrjPJGrVP");
	array_add(*data, "vpwwvQwCnhNQpSnLdVtrrZGZtZjdVSdJ");
	array_add(*data, "hfffwvTpvLwDpCLvDnQDHbmRRTcWRHMWWHWMmWMW");
	array_add(*data, "WHlNHWWldjpwntnWBPpPQFZFBFhZBZCZ");
	array_add(*data, "TqqvgvmgfmvDVLLfqqLsrFBRhrrBFJQBGPgPZGCR");
	array_add(*data, "mcDbcDmzLcmDDzfVzTQNjNzNztdzjNdwSHlH");
}


	priority :: (char : u8) -> int {
		if char >= #char "a" && char <= #char "z" {
			return char - #char "a" + 1;
		}
		else if char >= #char "A" && char <= #char "Z" {
			return char - #char "A" + 27; 
		}
		else {
			log_error("char % is out of range in priority", char);
			exit(1);
			return 0;
		}
	}

	table1 : Table(u8, int);	
	table2 : Table(u8, int);	
	table3 : Table(u8, int);


	total := 0;
	cumulative 	:= 0;

	for 0..data.count-1 {
		rucksack 	:= data[it];
		strLength 	:= rucksack.count;
		modit 		:= it % 3;

		for 0..strLength-1 {
			current := rucksack;
			current.count = 1;
			current.data += it;

			
			if modit == 0 {
				table_add(*table1, rucksack[it], priority(rucksack[it]));
			}
			else if modit == 1{
				table_add(*table2, rucksack[it], priority(rucksack[it]));
			}
			else {
				table_add(*table3, rucksack[it], priority(rucksack[it]));
			}
		}


		if modit == 2 {
			for table1 {
				key, iterValue 	:= it_index, it;
				value, success 	:= table_find(*table2, key);
				value2, success2 := table_find(*table3, key);
	
				if success && success2 {
					cumulative += priority(key);
					print("\n\nsuccess: %\n\n",  priority(key));
					break;
				}
			}

			table_reset(*table1);
			table_reset(*table2);
			table_reset(*table3);
			total += cumulative;
			cumulative = 0;

			print("Total: %", total);
		}
	}



}
